# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fighttype.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fighttype.proto',
  package='msg.fight',
  serialized_pb='\n\x0f\x66ighttype.proto\x12\tmsg.fight\"\xb7\x01\n\x0c\x46ightHitInfo\x12+\n\tstrongman\x18\x01 \x02(\x0b\x32\x18.msg.fight.FightUnitInfo\x12.\n\x0cweaknesslist\x18\x02 \x03(\x0b\x32\x18.msg.fight.FightUnitInfo\x12*\n\nattackmode\x18\x03 \x02(\x0e\x32\x16.msg.fight.eAttackMode\x12\x10\n\x08\x61ttackid\x18\x04 \x02(\x05\x12\x0c\n\x04time\x18\x05 \x02(\x05\"L\n\rFightUnitInfo\x12+\n\x08unittype\x18\x01 \x02(\x0e\x32\x19.msg.fight.eFightUnitType\x12\x0e\n\x06unitid\x18\x02 \x02(\t\")\n\tItemUnits\x12\x0e\n\x06itemid\x18\x01 \x01(\x05\x12\x0c\n\x04nums\x18\x02 \x01(\x05\"\'\n\tPropUnits\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05*\xc4\x01\n\x0e\x65\x42\x65haviourType\x12\x17\n\x13\x65\x42\x65haviourType_Walk\x10\x01\x12\x16\n\x12\x65\x42\x65haviourType_Run\x10\x02\x12\x17\n\x13\x65\x42\x65haviourType_Jump\x10\x03\x12\x19\n\x15\x65\x42\x65haviourType_Direct\x10\x04\x12\x19\n\x15\x65\x42\x65haviourType_Attack\x10\x05\x12\x18\n\x14\x65\x42\x65haviourType_Skill\x10\x06\x12\x18\n\x14\x65\x42\x65haviourType_Trump\x10\x07*|\n\x0e\x65\x46ightUnitType\x12\x17\n\x13\x65\x46ightUnitType_User\x10\x01\x12\x1a\n\x16\x65\x46ightUnitType_Monster\x10\x02\x12\x18\n\x14\x65\x46ightUnitType_Stuff\x10\x03\x12\x1b\n\x17\x65\x46ightUnitType_Follower\x10\x04*S\n\x0b\x65\x41ttackMode\x12\x15\n\x11\x65\x41ttackMode_skill\x10\x01\x12\x15\n\x11\x65\x41ttackMode_trump\x10\x02\x12\x16\n\x12\x65\x41ttackMode_pickup\x10\x03*\x8d\x01\n\x10\x65\x46ightScoreLevel\x12\x18\n\x14\x65\x46ightScoreLevel_SSS\x10\x01\x12\x17\n\x13\x65\x46ightScoreLevel_SS\x10\x02\x12\x16\n\x12\x65\x46ightScoreLevel_S\x10\x03\x12\x16\n\x12\x65\x46ightScoreLevel_A\x10\x04\x12\x16\n\x12\x65\x46ightScoreLevel_B\x10\x05*l\n\x0c\x65\x46ightResult\x12\x15\n\x11\x65\x46ightResult_LOSE\x10\x00\x12\x14\n\x10\x65\x46ightResult_WIN\x10\x01\x12\x16\n\x12\x65\x46ightResult_ERROR\x10\x02\x12\x17\n\x13\x65\x46ightResult_ESCAPE\x10\x03')

_EBEHAVIOURTYPE = _descriptor.EnumDescriptor(
  name='eBehaviourType',
  full_name='msg.fight.eBehaviourType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Walk', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Run', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Jump', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Direct', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Attack', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Skill', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eBehaviourType_Trump', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=379,
  serialized_end=575,
)

eBehaviourType = enum_type_wrapper.EnumTypeWrapper(_EBEHAVIOURTYPE)
_EFIGHTUNITTYPE = _descriptor.EnumDescriptor(
  name='eFightUnitType',
  full_name='msg.fight.eFightUnitType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eFightUnitType_User', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightUnitType_Monster', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightUnitType_Stuff', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightUnitType_Follower', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=577,
  serialized_end=701,
)

eFightUnitType = enum_type_wrapper.EnumTypeWrapper(_EFIGHTUNITTYPE)
_EATTACKMODE = _descriptor.EnumDescriptor(
  name='eAttackMode',
  full_name='msg.fight.eAttackMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eAttackMode_skill', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eAttackMode_trump', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eAttackMode_pickup', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=703,
  serialized_end=786,
)

eAttackMode = enum_type_wrapper.EnumTypeWrapper(_EATTACKMODE)
_EFIGHTSCORELEVEL = _descriptor.EnumDescriptor(
  name='eFightScoreLevel',
  full_name='msg.fight.eFightScoreLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eFightScoreLevel_SSS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightScoreLevel_SS', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightScoreLevel_S', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightScoreLevel_A', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightScoreLevel_B', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=789,
  serialized_end=930,
)

eFightScoreLevel = enum_type_wrapper.EnumTypeWrapper(_EFIGHTSCORELEVEL)
_EFIGHTRESULT = _descriptor.EnumDescriptor(
  name='eFightResult',
  full_name='msg.fight.eFightResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='eFightResult_LOSE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightResult_WIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightResult_ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eFightResult_ESCAPE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=932,
  serialized_end=1040,
)

eFightResult = enum_type_wrapper.EnumTypeWrapper(_EFIGHTRESULT)
eBehaviourType_Walk = 1
eBehaviourType_Run = 2
eBehaviourType_Jump = 3
eBehaviourType_Direct = 4
eBehaviourType_Attack = 5
eBehaviourType_Skill = 6
eBehaviourType_Trump = 7
eFightUnitType_User = 1
eFightUnitType_Monster = 2
eFightUnitType_Stuff = 3
eFightUnitType_Follower = 4
eAttackMode_skill = 1
eAttackMode_trump = 2
eAttackMode_pickup = 3
eFightScoreLevel_SSS = 1
eFightScoreLevel_SS = 2
eFightScoreLevel_S = 3
eFightScoreLevel_A = 4
eFightScoreLevel_B = 5
eFightResult_LOSE = 0
eFightResult_WIN = 1
eFightResult_ERROR = 2
eFightResult_ESCAPE = 3



_FIGHTHITINFO = _descriptor.Descriptor(
  name='FightHitInfo',
  full_name='msg.fight.FightHitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strongman', full_name='msg.fight.FightHitInfo.strongman', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weaknesslist', full_name='msg.fight.FightHitInfo.weaknesslist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackmode', full_name='msg.fight.FightHitInfo.attackmode', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackid', full_name='msg.fight.FightHitInfo.attackid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='msg.fight.FightHitInfo.time', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=214,
)


_FIGHTUNITINFO = _descriptor.Descriptor(
  name='FightUnitInfo',
  full_name='msg.fight.FightUnitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unittype', full_name='msg.fight.FightUnitInfo.unittype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unitid', full_name='msg.fight.FightUnitInfo.unitid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=292,
)


_ITEMUNITS = _descriptor.Descriptor(
  name='ItemUnits',
  full_name='msg.fight.ItemUnits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='msg.fight.ItemUnits.itemid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nums', full_name='msg.fight.ItemUnits.nums', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=294,
  serialized_end=335,
)


_PROPUNITS = _descriptor.Descriptor(
  name='PropUnits',
  full_name='msg.fight.PropUnits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='msg.fight.PropUnits.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='msg.fight.PropUnits.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=337,
  serialized_end=376,
)

_FIGHTHITINFO.fields_by_name['strongman'].message_type = _FIGHTUNITINFO
_FIGHTHITINFO.fields_by_name['weaknesslist'].message_type = _FIGHTUNITINFO
_FIGHTHITINFO.fields_by_name['attackmode'].enum_type = _EATTACKMODE
_FIGHTUNITINFO.fields_by_name['unittype'].enum_type = _EFIGHTUNITTYPE
DESCRIPTOR.message_types_by_name['FightHitInfo'] = _FIGHTHITINFO
DESCRIPTOR.message_types_by_name['FightUnitInfo'] = _FIGHTUNITINFO
DESCRIPTOR.message_types_by_name['ItemUnits'] = _ITEMUNITS
DESCRIPTOR.message_types_by_name['PropUnits'] = _PROPUNITS

class FightHitInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIGHTHITINFO

  # @@protoc_insertion_point(class_scope:msg.fight.FightHitInfo)

class FightUnitInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIGHTUNITINFO

  # @@protoc_insertion_point(class_scope:msg.fight.FightUnitInfo)

class ItemUnits(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEMUNITS

  # @@protoc_insertion_point(class_scope:msg.fight.ItemUnits)

class PropUnits(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPUNITS

  # @@protoc_insertion_point(class_scope:msg.fight.PropUnits)


# @@protoc_insertion_point(module_scope)
