# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teamtype.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teamtype.proto',
  package='msg.team',
  serialized_pb='\n\x0eteamtype.proto\x12\x08msg.team\"\x9c\x01\n\x0cTeamBaseInfo\x12\x0e\n\x06teamid\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rea\x18\x02 \x01(\x05\x12\x0e\n\x06target\x18\x03 \x01(\x05\x12\x12\n\ndifficulty\x18\x04 \x01(\x05\x12\x10\n\x08leaderid\x18\x05 \x01(\t\x12\x12\n\nleadername\x18\x06 \x01(\t\x12\x12\n\ntotalcount\x18\x07 \x01(\x05\x12\x10\n\x08\x63urcount\x18\x08 \x01(\x05\"o\n\x0eTeamBaseMember\x12\x10\n\x08memberid\x18\x01 \x01(\t\x12\x12\n\nmembername\x18\x02 \x01(\t\x12\x10\n\x08teamrole\x18\x03 \x01(\x05\x12\x13\n\x0bmemberlevel\x18\x04 \x01(\x05\x12\x10\n\x08racetype\x18\x05 \x01(\x05\"\x9d\x01\n\x08RoleInfo\x12\x0e\n\x06unitid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x10\n\x08racetype\x18\x04 \x01(\x05\x12\x10\n\x08isyellow\x18\x05 \x01(\x08\x12\x14\n\x0cisyearyellow\x18\x06 \x01(\x08\x12\x15\n\rissuperyellow\x18\x07 \x01(\x08\x12\x13\n\x0byellowlevel\x18\x08 \x01(\x05')




_TEAMBASEINFO = _descriptor.Descriptor(
  name='TeamBaseInfo',
  full_name='msg.team.TeamBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teamid', full_name='msg.team.TeamBaseInfo.teamid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='msg.team.TeamBaseInfo.area', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='msg.team.TeamBaseInfo.target', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='msg.team.TeamBaseInfo.difficulty', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leaderid', full_name='msg.team.TeamBaseInfo.leaderid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leadername', full_name='msg.team.TeamBaseInfo.leadername', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalcount', full_name='msg.team.TeamBaseInfo.totalcount', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curcount', full_name='msg.team.TeamBaseInfo.curcount', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=185,
)


_TEAMBASEMEMBER = _descriptor.Descriptor(
  name='TeamBaseMember',
  full_name='msg.team.TeamBaseMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='memberid', full_name='msg.team.TeamBaseMember.memberid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='membername', full_name='msg.team.TeamBaseMember.membername', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='teamrole', full_name='msg.team.TeamBaseMember.teamrole', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memberlevel', full_name='msg.team.TeamBaseMember.memberlevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='racetype', full_name='msg.team.TeamBaseMember.racetype', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=298,
)


_ROLEINFO = _descriptor.Descriptor(
  name='RoleInfo',
  full_name='msg.team.RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unitid', full_name='msg.team.RoleInfo.unitid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg.team.RoleInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='msg.team.RoleInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='racetype', full_name='msg.team.RoleInfo.racetype', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isyellow', full_name='msg.team.RoleInfo.isyellow', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isyearyellow', full_name='msg.team.RoleInfo.isyearyellow', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='issuperyellow', full_name='msg.team.RoleInfo.issuperyellow', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yellowlevel', full_name='msg.team.RoleInfo.yellowlevel', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=301,
  serialized_end=458,
)

DESCRIPTOR.message_types_by_name['TeamBaseInfo'] = _TEAMBASEINFO
DESCRIPTOR.message_types_by_name['TeamBaseMember'] = _TEAMBASEMEMBER
DESCRIPTOR.message_types_by_name['RoleInfo'] = _ROLEINFO

class TeamBaseInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMBASEINFO

  # @@protoc_insertion_point(class_scope:msg.team.TeamBaseInfo)

class TeamBaseMember(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMBASEMEMBER

  # @@protoc_insertion_point(class_scope:msg.team.TeamBaseMember)

class RoleInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLEINFO

  # @@protoc_insertion_point(class_scope:msg.team.RoleInfo)


# @@protoc_insertion_point(module_scope)
